### ISSUE TITLE
Legge til diagrammer

### ISSUE THREAD

**Issue by krissmed** [krissmed/DAFE1200-2021#26]
Tenker at det er greit å legge til noen diagrammer for å ha noe å vise til. Tenkte på noe så enkelt som [dette ](http://www.coding-dude.com/wp/html5/bar-chart-html/) men jeg vet ikke om det er innafor å ta med kode som vi ikke har skrevet selv. Hvis ikke så er det ikke noe vi trenger å bruke lang tid på

**Comment by erlingstaff** [comment]
Gammel issue. Løst.
