### ISSUE TITLE
Ideer til løsning

### ISSUE THREAD

**Issue by krissmed** [krissmed/DAFE1200-2021#3]
Vi vet ikke hva slags oppgavetekst som kommer, så bare skriv alt man kommer på!

**Comment by krissmed** [comment]
- Ny rombestillingsside for Oslomet
- Deskodora

**Comment by VetEnd** [comment]
En app med oversikt over strøm forbruk 🤔

**Comment by krissmed** [comment]
> En app med oversikt over strøm forbruk 🤔

Er ikke det samme ideen vi hadde i fjor?

**Comment by krissmed** [comment]
Salg av brukt kontorutstyr. I stedet for å kaste f.eks gamle skjermer, kan man selge dem billig på nettsiden og unngå e-avfall.

**Comment by erlingstaff** [comment]
Gammel issue. Løst.
