### ISSUE TITLE
Burde les mer knappen automatisk skrolle til første "kort" eller fortsatt være på toppen?

### ISSUE THREAD

**Issue by krissmed** [krissmed/DAFE1200-2021#33]
Skal man skrolle hit?
![image](https://user-images.githubusercontent.com/29783486/140706368-d924c253-78c8-4723-9010-5f0d8f1ab260.png)

Eller hit?
![image](https://user-images.githubusercontent.com/29783486/140706420-a40307fb-3682-482b-a5f3-7cb9ea84a099.png)

**Comment by OleJorgenKnoph** [comment]
Tenker øverste som da har en liten illustrerende forside til det en ønsker å lese mer om

**Comment by erlingstaff** [comment]
Gammel issue. Løst.
