### ISSUE TITLE
Skalering av tekst

### ISSUE THREAD

**Issue by krissmed** [krissmed/DAFE1200-2021#34]
Teksten strekker seg langt ned når siden blir smalere. Bruk breakpoint for å skalere tekst og fjerne bilde når siden skaleres

**Comment by OleJorgenKnoph** [comment]
Kan også benytte "min-height:" så skalerer siden ette teksten

**Comment by krissmed** [comment]
Den er allerede min-height. Problemet er at den blir veldig lang bl.a på grunn av bildet
![image](https://user-images.githubusercontent.com/29783486/140707744-3e46074c-66fe-4275-b5c9-b90f160de8e2.png)

**Comment by krissmed** [comment]
Typiske breakpoint verdier: https://www.w3schools.com/howto/howto_css_media_query_breakpoints.asp

**Comment by erlingstaff** [comment]
Løst
