### ISSUE TITLE
Kildeutfylling

### ISSUE THREAD

**Issue by krissmed** [krissmed/DAFE1200-2021#37]
Fyll ut kilder i henhold til apa 6th. 
https://kildekompasset.no/referansestiler/apa-6th/

**Comment by erlingstaff** [comment]
https://www.stickpng.com/img/download/580b57fcd9996e24bc43c43d pilkilde

**Comment by erlingstaff** [comment]
https://blog.cwf-fcf.org/wp-content/uploads/2020/03/electronics-dump-172777435.jpg bgimg

**Comment by krissmed** [comment]
https://www.epa.gov/lmop/frequent-questions-about-landfill-gas

**Comment by krissmed** [comment]
https://docs.google.com/document/d/18leOfNzwUxOi3zi_y0RYoi8DIbaTN81uLxuI0pcd2JM/edit?usp=sharing

**Comment by erlingstaff** [comment]
Gammel issue. Løst.
