### ISSUE TITLE
endre fargen på ned-pilene slik at det blir større kontrast

### ISSUE THREAD

**Issue by erlingstaff** [krissmed/DAFE1200-2021#47]
@krissmed kan du gjøre dette med den samme editoren du brukte tidligere?

**Comment by krissmed** [comment]
Det skal jeg fikse👍

**Comment by krissmed** [comment]
@erlingstaff Hvlken farge vil du ha det i?

**Comment by OleJorgenKnoph** [comment]
<img width="768" alt="Skjermbilde 2021-11-25 kl  11 59 06" src="https://user-images.githubusercontent.com/70891970/143429396-5d465f79-b15e-46cc-b6ad-83aab3c18a7d.png">
Funker ikke fullstendig på norsk index.html

**Comment by erlingstaff** [comment]
Ordnet
